### ISSUE TITLE
When will the code be open?

### ISSUE THREAD

**Issue by zhouying12** [stevenyangyj/Emma-Alfworld#1]
When will the code be open sourced?

**Comment by stevenyangyj** [comment]
Thank you for your interest and apologize for the slow release (I've been a bit behind due to my PhD defense). Moreover, the original codebase is highly coupled to the internal developing environment adopted by JD Explore Academy, I will remove unnecessary dependencies and refactor some components for public reproducibility. 

Thanks again for your patience!

**Comment by Shreyojit** [comment]
hello this is such an exciting project but when will it be released totally as of now i havent seen ai2thor.controller being used here,I am eagerly waiting for the code

**Comment by stevenyangyj** [comment]
> hello this is such an exciting project but when will it be released totally as of now i havent seen ai2thor.controller being used here,I am eagerly waiting for the code

Hi! Thanks so much for your interest. The ai2thor environment in the original project is deployed in a local machine and communicates with the training server using the socket library. And the implementation is highly customized **so you need to write your own communication interface** (refer to [this issue](https://github.com/stevenyangyj/Emma-Alfworld/issues/7)). The reason behind this design is the ai2thor version used by alfworld cannot be successfully installed in a headless server, while you need this cloud gpu server to train the VLM agent.
